const CACHE_LOAD_RETRY_ATTEMPS = 1;
const CACHE_LOAD_RETRY_DELAY_MS = 300;
const CACHE_ITEM_LOCK_TIMEOUT_MS = 60000;
const CACHE_ITEMS_LIMIT = 50;

export {
  CACHE_LOAD_RETRY_ATTEMPS,
  CACHE_LOAD_RETRY_DELAY_MS,
  CACHE_ITEM_LOCK_TIMEOUT_MS,
  CACHE_ITEMS_LIMIT,
};
