enum EnvironmentNames {
  DB_GENERAL_PATH = "DB_GENERAL_PATH",
  DB_CATALOG_PATH = "DB_CATALOG_PATH",
  DB_OPERATIONS_PATH = "DB_OPERATIONS_PATH",
  DATA_RECORDS_ON_PAGE = "DATA_RECORDS_ON_PAGE",
  PUBLIC_BLOB_STORAGE_CATEGORIES_URL = "PUBLIC_BLOB_STORAGE_CATEGORIES_URL",
  PUBLIC_BLOB_STORAGE_PRODUCTS_URL = "PUBLIC_BLOB_STORAGE_PRODUCTS_URL",
}

export { EnvironmentNames };
