const FILE_EXTENSIION_XML = ".xml";
const FILE_EXTENSIION_ZIP = ".zip";
const FILE_EXTENSIION_JPG = ".jpg";
const FILE_EXTENSIION_PNG = ".jpg";

export {
  FILE_EXTENSIION_XML,
  FILE_EXTENSIION_ZIP,
  FILE_EXTENSIION_JPG,
  FILE_EXTENSIION_PNG,
};
