const FILE_EXTENSIION_XML = ".xml";
const FILE_EXTENSIION_ZIP = ".zip";
const FILE_EXTENSIION_JPG = ".jpg";
const FILE_EXTENSIION_PNG = ".jpg";
const FILE_EXTENSIION_DB = ".db";
const FILE_EXTENSIION_DB_WAL = ".db-wal";
const FILE_EXTENSIION_DB_SHM = ".db-shm";

export {
  FILE_EXTENSIION_XML,
  FILE_EXTENSIION_ZIP,
  FILE_EXTENSIION_JPG,
  FILE_EXTENSIION_PNG,
  FILE_EXTENSIION_DB,
  FILE_EXTENSIION_DB_WAL,
  FILE_EXTENSIION_DB_SHM,
};
